Life: Grid Class Reference
Grid Class Reference
#include <Grid.h>
Public Member Functions
Grid ()
Grid (int nSquaresOnASide)
bool setCellOccupant (int r, int c, occupationStatus g)
int getNumDoodle ()
bool setNumDoodle (int num)
bool setNumAnt (int num)
int getNumAnt ()
occupationStatus getCellOccupant (int r, int c)
bool printGrid ()
bool setSeed (int s)
virtual ~Grid ()
int getNumCells ()
bool setRand ()
bool setPause (char c)
char getPause ()
int getRand ()
Cell ** getGrid ()
Cell getCell (int r, int c)
bool setCellOrganism (int r, int c, Organism *o)
Organism * getCellOrganism (int r, int c)
Private Attributes
int numDoodle = 0
int numAnt = 0
Cell ** myGridCells_ptr_array = (Cell**)nullptr
int seed = 0
int nCells = 0
char pause = 'n'
int randomVal = 0
Constructor & Destructor Documentation
Grid() [1/2]
Grid::Grid ()
Grid::Grid() is the default constructor for the grid
Parameters
none
Returns
none
Grid() [2/2]
Grid::Grid (int nSquaresOnASide)
Grid::Grid(int nSquaresOnASide) is a constructor for the grid
Parameters
int nSquaresOnASide is the number of squares for one side
Returns
none
References myGridCells_ptr_array, and nCells.
~Grid()
Grid::~Grid () virtual
Grid::~Grid() is the default destructor for a grid
Parameters
none
Returns
none
References myGridCells_ptr_array, nCells, and Cell::~Cell().
Referenced by Tests2::antsBreedTest(), Tests2::antsDieTest(), Tests2::antsMoveTest(), Tests2::doodleBreedTest(), Tests2::doodleDietest(), Tests2::doodleEatTest(), Tests2::doodleMoveTest(), Tests2::gridTest(), Tests2::makeDoodlesTest(), and Tests2::OrganismTest().
Member Function Documentation
getCell()
Cell Grid::getCell (int r, int c)
getCellOccupant()
occupationStatus Grid::getCellOccupant (int r, int c)
Grid::getCellOccupant() is a Function that gets the occupation status for a cell
Parameters
int r is the row of the grid
int c is the column of the grid
Returns
occupation status of a given cell
References Cell::getOccupant(), and myGridCells_ptr_array.
Referenced by Tests2::antsBreedTest(), Tests2::antsMoveTest(), Tests2::doodleBreedTest(), Tests2::doodleEatTest(), Tests2::doodleMoveTest(), Ant::getRandCell(), Doodlebug::getRandCell(), Tests2::gridTest(), Tests2::makeAntsTest(), Tests2::makeDoodlesTest(), Organism::numPossCells(), Doodlebug::numPossCells(), Tests2::OrganismTest(), and Production::runProduction().
getCellOrganism()
Organism * Grid::getCellOrganism (int r, int c)
Grid::getCellOrganism() is a Function that gets the Organism* for a cell
Parameters
int r is the row of the grid
int c is the column of the grid
Returns
organism* of a given cell
References Cell::getOrganism(), and myGridCells_ptr_array.
Referenced by Tests2::antsDieTest(), Tests2::antsMoveTest(), Tests2::doodleDietest(), Tests2::doodleMoveTest(), Doodlebug::eat(), Ant::move(), Doodlebug::move(), Production::runProduction(), and Doodlebug::step().
getGrid()
Cell ** Grid::getGrid ()
Grid::getGrid gets the pointer to the first cell in the gird, which is the pointer to the grid
Parameters
none
Returns
returns a pointer to the grid
References myGridCells_ptr_array.
getNumAnt()
int Grid::getNumAnt ()
Grid::getNumAnt() Function gets the number of ants
Parameters
none
Returns
is the number of ants on the grid
References numAnt.
Referenced by Tests2::antsBreedTest(), Ant::breed(), Doodlebug::eat(), Production::runProduction(), and Ant::step().
getNumCells()
int Grid::getNumCells ()
Grid::getNumCells() is a Function that gets the number of cells in the grid
Returns
the number of cells in the grid
References nCells.
Referenced by Ant::getRandCell(), Doodlebug::getRandCell(), Organism::numPossCells(), Doodlebug::numPossCells(), Tests2::OrganismTest(), and Production::runProduction().
getNumDoodle()
int Grid::getNumDoodle ()
Grid::getNumDoodle() Function gets the number of doodlebugs
Returns
is the number of doodlebugs on the grid
References numDoodle.
Referenced by Doodlebug::breedDoodle(), Production::runProduction(), and Doodlebug::step().
getPause()
char Grid::getPause ()
Grid::getPause get the status pause functionality of the grid
Parameters
none
Returns
bool if the function worked
References pause.
Referenced by Production::runProduction().
getRand()
int Grid::getRand ()
Grid::getRand get the randomVal field of the grid
Parameters
none
Returns
bool if the function worked
References randomVal.
printGrid()
bool Grid::printGrid ()
Grid::printGrid() will print the grid to the console
Parameters
none
Returns
bool if it worked
References ant, doodlebug, empty, myGridCells_ptr_array, and nCells.
Referenced by Tests2::antsMoveTest(), Tests2::doodleMoveTest(), Production::Production(), and Production::runProduction().
setCellOccupant()
bool Grid::setCellOccupant (int r, int c, occupationStatus g)
Grid::setCellOccupant() is a Function that sets the occupation status for a cell
Parameters
int r is the row of the grid
int c is the column of the grid
occupationStatus g is the occupation status that you are trying to pass on a given cell
Returns
bool returns the status of if this function worked
References myGridCells_ptr_array, and Cell::setOccupant().
Referenced by Tests2::antsBreedTest(), Tests2::antsDieTest(), Tests2::antsMoveTest(), Ant::breed(), Doodlebug::breedDoodle(), Tests2::doodleBreedTest(), Tests2::doodleDietest(), Tests2::doodleEatTest(), Tests2::doodleMoveTest(), Doodlebug::eat(), Tests2::gridTest(), Tests2::makeAntsTest(), Tests2::makeDoodlesTest(), Ant::move(), Doodlebug::move(), Tests2::organismNeighborTest(), Tests2::organismRandCellTest(), Tests2::OrganismTest(), Production::Production(), Ant::~Ant(), and Doodlebug::~Doodlebug().
setCellOrganism()
bool Grid::setCellOrganism (int r, int c, Organism * o)
Grid::setCellOrganism() is a Function that sets organism of a cell
Parameters
int r is the row of the grid
int c is the column of the grid
Organism * g is the pointer to an organism
Returns
bool returns the status of if this function worked
References myGridCells_ptr_array, and Cell::setOrganism().
Referenced by Tests2::antsBreedTest(), Tests2::antsDieTest(), Tests2::antsMoveTest(), Ant::breed(), Doodlebug::breedDoodle(), Tests2::doodleBreedTest(), Tests2::doodleDietest(), Tests2::doodleEatTest(), Tests2::doodleMoveTest(), Doodlebug::eat(), Ant::move(), Doodlebug::move(), Tests2::organismNeighborTest(), Tests2::organismRandCellTest(), Production::Production(), Ant::~Ant(), and Doodlebug::~Doodlebug().
setNumAnt()
bool Grid::setNumAnt (int num)
Grid::getNumAnt() Function sets the number of Ants
Returns
a bool on if this function ran or not
References numAnt.
Referenced by Ant::breed(), Doodlebug::eat(), Production::Production(), and Ant::step().
setNumDoodle()
bool Grid::setNumDoodle (int num)
Grid::getNumDoodle() Function sets the number of doodlebugs
Parameters
int num, the total number of doodlebugs
Returns
a bool on if this function ran or not
References numDoodle.
Referenced by Doodlebug::breedDoodle(), Production::Production(), and Doodlebug::step().
setPause()
bool Grid::setPause (char c)
Grid::setPause set the status pause functionality of the grid
Parameters
none
Returns
bool if the function worked
References pause.
Referenced by Production::Production().
setRand()
bool Grid::setRand ()
Grid::setRand() sets the randomVal field of the grid
Parameters
none
Returns
bool if the function worked
References randomVal.
setSeed()
bool Grid::setSeed (int s)
Grid::setSeed sets the seed of the program
Parameters
none
Returns
bool if the function worked
References seed.
Field Documentation
myGridCells_ptr_array
Cell** Grid::myGridCells_ptr_array = (Cell**)nullptr private
Referenced by getCellOccupant(), getCellOrganism(), getGrid(), Grid(), printGrid(), setCellOccupant(), setCellOrganism(), and ~Grid().
nCells
int Grid::nCells = 0 private
Referenced by getNumCells(), Grid(), printGrid(), and ~Grid().
numAnt
int Grid::numAnt = 0 private
Referenced by getNumAnt(), and setNumAnt().
numDoodle
int Grid::numDoodle = 0 private
Referenced by getNumDoodle(), and setNumDoodle().
pause
char Grid::pause = 'n' private
Referenced by getPause(), and setPause().
randomVal
int Grid::randomVal = 0 private
Referenced by getRand(), and setRand().
seed
int Grid::seed = 0 private
Referenced by setSeed().
The documentation for this class was generated from the following files:
Grid.h
Grid.cpp