Life: Ant Class Reference
Ant Class Reference
#include <Ant.h>
Public Member Functions
Ant ()
Ant (int r, int c, Grid *ptr)
bool move ()
bool breed ()
bool step ()
bool increm ()
bool setBreedCnt (int i)
bool setRowAndCol (int i, int j)
bool setGridPtr (Grid *a)
struct Organism::Coordinates getRandCell (int row, int col, Grid *g)
~Ant ()
Public Member Functions inherited from Organism
Organism ()
Organism (bool b)
bool isPrey ()
void setAmAnt (bool b)
virtual ~Organism ()
virtual int numPossCells (int row, int col, Grid *g)
Private Attributes
int row = 0
int col = 0
int breedCnt = 0
Grid * g = nullptr
Constructor & Destructor Documentation
Ant() [1/2]
Ant::Ant ()
Ant::Ant() is the basic constructor for the ant class
Parameters
none
Returns
none
Referenced by breed(), and Tests2::organismRandCellTest().
Ant() [2/2]
Ant::Ant (int r, int c, Grid * ptr)
Ant::Ant() is another constructor for the ant class, placing the ant object at the location on the grid specified by the row and column parameters
Parameters
int r, the row where the ant will be constructed
int c, the column where the ant will be constructed
int life, the amount of ticks the ant object has been alive on the board
Returns
none
References col, g, and row.
~Ant()
Ant::~Ant ()
Ant::~Ant is a destructor for the ant class
Parameters
none indicating that a ant object has died
References col, empty, g, row, Grid::setCellOccupant(), Grid::setCellOrganism(), and setGridPtr().
Referenced by Tests2::antsBreedTest(), Tests2::antsDieTest(), Tests2::antsMoveTest(), Doodlebug::eat(), Tests2::makeAntsTest(), and Tests2::OrganismTest().
Member Function Documentation
breed()
bool Ant::breed () virtual
Ant::breed() should check the cells around the ant object and if another ant in is a neighboring cell, then they will produce a new ant object in a free space
Parameters
Grid* g grid we are on
Returns
status true if ant breed
Implements Organism.
References ant, Ant(), Organism::Coordinates::cellCol, Organism::Coordinates::cellRow, col, g, Grid::getNumAnt(), getRandCell(), increm(), row, setBreedCnt(), Grid::setCellOccupant(), Grid::setCellOrganism(), and Grid::setNumAnt().
Referenced by Tests2::antsBreedTest(), and step().
getRandCell()
struct Ant::Coordinates Ant::getRandCell (int row, int col, Grid * g) virtual
Ant::GetRandCell takes an array of pointers to cells and returns a pseudo-random cell that is a neighbor of the input cell (row and cel)..
Parameters
int row, the row that this cell is on
int col, the column that this cell is on
Grid g is the grid of cells
Returns
output, a struct Coordinates which represents the row and column of the randomly chosen cell
Reimplemented from Organism.
References Organism::Coordinates::cellCol, Organism::Coordinates::cellRow, col, empty, g, Grid::getCellOccupant(), Grid::getNumCells(), Organism::numPossCells(), and row.
Referenced by breed(), move(), and Tests2::organismRandCellTest().
increm()
bool Ant::increm ()
Ant::increm()- used to increment the breed counters inside of the ant.
Parameters
none
Returns
bool result true if the function ran properly
References breedCnt.
Referenced by breed(), and step().
move()
bool Ant::move () virtual
Ant::move() should move an ant object to a neighboring cell
Parameters
none
Returns
status, true if the ant object moved
Implements Organism.
References ant, Organism::Coordinates::cellCol, Organism::Coordinates::cellRow, col, empty, g, Grid::getCellOrganism(), getRandCell(), row, Grid::setCellOccupant(), Grid::setCellOrganism(), and setRowAndCol().
Referenced by Tests2::antsMoveTest(), and step().
setBreedCnt()
bool Ant::setBreedCnt (int i)
Ant::setBreedCnt Sets the Breed Count inside of the ant
Parameters
int i the new count to i
bool result true if the function worked
References breedCnt.
Referenced by breed().
setGridPtr()
bool Ant::setGridPtr (Grid * a)
Ant::setGridPtr Sets the grid pointer for the ant
Parameters
none
Returns
bool true if the function worked
References g.
Referenced by ~Ant().
setRowAndCol()
bool Ant::setRowAndCol (int i, int j)
Ant::setRowAndCol set the row and column of the Ant
Parameters
int i the new row
int j the new column
bool result true if function worked
References col, and row.
Referenced by move().
step()
bool Ant::step () virtual
Ant::Step() performs a move and breed if the conditions for moving and breeding are met.
Parameters
none
Returns
bool if the step worked
Implements Organism.
References breed(), breedCnt, col, g, Grid::getNumAnt(), increm(), move(), Organism::numPossCells(), row, and Grid::setNumAnt().
Field Documentation
breedCnt
int Ant::breedCnt = 0 private
Referenced by increm(), setBreedCnt(), and step().
col
int Ant::col = 0 private
Referenced by Ant(), breed(), getRandCell(), move(), setRowAndCol(), step(), and ~Ant().
g
Grid* Ant::g = nullptr private
Referenced by Ant(), breed(), getRandCell(), move(), setGridPtr(), step(), and ~Ant().
row
int Ant::row = 0 private
Referenced by Ant(), breed(), getRandCell(), move(), setRowAndCol(), step(), and ~Ant().
The documentation for this class was generated from the following files:
Ant.h
Ant.cpp