Life: Organism Class Reference
Organism Class Reference abstract
#include <Organism.h>
Data Structures
struct Coordinates
Public Member Functions
Organism ()
Organism (bool b)
bool isPrey ()
virtual bool move ()=0
virtual bool breed ()=0
virtual bool step ()=0
void setAmAnt (bool b)
virtual ~Organism ()
virtual int numPossCells (int row, int col, Grid *g)
virtual struct Coordinates getRandCell (int row, int col, Grid *g)
Private Attributes
bool amAnt = false
Constructor & Destructor Documentation
Organism() [1/2]
Organism::Organism ()
Organism::Organism() is default constructor for a Organism
Parameters
none
Returns
none
Organism() [2/2]
Organism::Organism (bool b)
Organism::Organism() is the Secondary Constructor
Parameters
bool b is whether the organism is an ant
Returns
none
References amAnt.
~Organism()
Organism::~Organism () virtual
Organism::~Organism is the destructor
Parameters
none
Returns
none
Member Function Documentation
breed()
virtual bool Organism::breed () pure virtual
Implemented in Doodlebug, and Ant.
getRandCell()
struct Organism::Coordinates Organism::getRandCell (int row, int col, Grid * g) virtual
Organism::GetRandCell() takes a grid and a row column pair, and returns a randomly picked neighboring cell with neighbors being defined as 4-connected
Parameters
int row, the row of the cell to a get random neighboring cell from
int col, the row of the cell to a get random neighboring cell from
Grid* g, the grid on which you are getting the random cell
Returns
output, a Coordinate struct, which contains the row, column coordinates of the random neighboring cell
Reimplemented in Doodlebug, and Ant.
References Organism::Coordinates::cellCol, Organism::Coordinates::cellRow, empty, and numPossCells().
Referenced by Doodlebug::breedDoodle(), and Doodlebug::move().
isPrey()
bool Organism::isPrey ()
Organism::isPrey() is a function used to tell if an organism is prey
Parameters
none
Returns
bool returns if the organism is an ant
References amAnt.
move()
virtual bool Organism::move () pure virtual
Implemented in Doodlebug, and Ant.
numPossCells()
int Organism::numPossCells (int row, int col, Grid * g) virtual
Organism::numPossCells checks how many cells neighboring a cell are empty and returns the count of all the empty neighbors
Parameters
int row, the row that this cell is on
int col, the column that this cell is on
Grid* g, is the grid of cells
Returns
int the number of empty neighbors
Reimplemented in Doodlebug.
References empty, Grid::getCellOccupant(), and Grid::getNumCells().
Referenced by Ant::getRandCell(), getRandCell(), Tests2::organismNeighborTest(), Tests2::OrganismTest(), Ant::step(), and Doodlebug::step().
setAmAnt()
void Organism::setAmAnt (bool b)
Organism::setAmAnt() is a function used to set if an organism is an ant
Parameters
bool b, the status of the organism, true if ant false otherwise
Returns
void
References amAnt.
step()
virtual bool Organism::step () pure virtual
Implemented in Doodlebug, and Ant.
Referenced by Production::runProduction().
Field Documentation
amAnt
bool Organism::amAnt = false private
Referenced by isPrey(), Organism(), and setAmAnt().
The documentation for this class was generated from the following files:
Organism.h
Organism.cpp