Life: Doodlebug Class Reference
Doodlebug Class Reference
#include <Doodlebug.h>
Public Member Functions
Doodlebug ()
Doodlebug (int r, int c, Grid *ptr)
bool move ()
bool breed ()
bool breedDoodle ()
bool eat ()
int getStarveCnt ()
bool setStarveCnt (int s)
~Doodlebug ()
bool step ()
bool increm ()
bool setBreedCnt (int i)
int numPossCells (int row, int col, Grid *g)
bool setGridPtr (Grid *a)
bool setRowAndCol (int i, int j)
struct Organism::Coordinates getRandCell (int row, int col, Grid *g)
Public Member Functions inherited from Organism
Organism ()
Organism (bool b)
bool isPrey ()
void setAmAnt (bool b)
virtual ~Organism ()
Private Attributes
int row = 0
int col = 0
int starveCnt = 0
int breedCnt = 0
Grid * g = nullptr
Constructor & Destructor Documentation
Doodlebug() [1/2]
Doodlebug::Doodlebug ()
Doodlebug::Doodlebug() Default Constructor
Parameters
false is set for the organism input to tell the organism that it is not an ant
Returns
none
Referenced by breedDoodle().
Doodlebug() [2/2]
Doodlebug::Doodlebug (int r, int c, Grid * ptr)
Doodlebug::Doodlebug():Organism() Constructor
Parameters
int r, The row the doodlebug should be constructed on
int c, The col the doodlebug should be constructed on
Grid * ptr, The pointer to the grid the doodlebug is geing created on
false is set for the organism input to tell the organism that it is not an ant Doodlebug will have a Starve Counter and a Breed Counter it will also have a row and col for its location
Returns
none
References col, g, and row.
~Doodlebug()
Doodlebug::~Doodlebug ()
Doodlebug::~Doodlebug() Destructor, used to remove a pointer to a doodlebug
Parameters
none
Returns
none
References col, empty, g, row, Grid::setCellOccupant(), Grid::setCellOrganism(), and setGridPtr().
Referenced by Tests2::antsMoveTest(), Tests2::doodleBreedTest(), Tests2::doodleDietest(), Tests2::doodleEatTest(), Tests2::doodleMoveTest(), Tests2::makeDoodlesTest(), and step().
Member Function Documentation
breed()
bool Doodlebug::breed () virtual
Implements Organism.
breedDoodle()
bool Doodlebug::breedDoodle ()
Doodlebug::breed(), finds a random unoccupied neighboring cell and creates a new doodlebug inside it. Breeding does NOT take precidence over death
Parameters
none
Returns
bool returns true if the bug was able to breed
References Organism::Coordinates::cellCol, Organism::Coordinates::cellRow, col, doodlebug, Doodlebug(), g, Grid::getNumDoodle(), Organism::getRandCell(), row, setBreedCnt(), Grid::setCellOccupant(), Grid::setCellOrganism(), and Grid::setNumDoodle().
Referenced by Tests2::doodleBreedTest(), and step().
eat()
bool Doodlebug::eat ()
Doodlebug::eat() finds a neighboring cell that contains an ant and resets the doodlebug's starve counter, also destructs the ant Eating takes precedence over the majority of other actions
Parameters
none
Returns
bool returns true if the bug was able to eat
References Organism::Coordinates::cellCol, Organism::Coordinates::cellRow, col, doodlebug, empty, g, Grid::getCellOrganism(), Grid::getNumAnt(), getRandCell(), row, Grid::setCellOccupant(), Grid::setCellOrganism(), Grid::setNumAnt(), setRowAndCol(), setStarveCnt(), and Ant::~Ant().
Referenced by Tests2::doodleEatTest(), and step().
getRandCell()
struct Doodlebug::Coordinates Doodlebug::getRandCell (int row, int col, Grid * g) virtual
GetRandCell takes an array of pointers to cells and returns a pseudo-random cell that neighbors the input row column pair.
Parameters
int row, the row that this cell is on
int col, the column that this cell is on
Grid g is the grid of cells
Returns
output, a struct Coordinates which represents the row and column of the randomly chosen cell
Reimplemented from Organism.
References ant, Organism::Coordinates::cellCol, Organism::Coordinates::cellRow, col, g, Grid::getCellOccupant(), Grid::getNumCells(), numPossCells(), and row.
Referenced by eat().
getStarveCnt()
int Doodlebug::getStarveCnt ()
Doodlebug::getStarveCnt() gets the starve count
Parameters
none
Returns
the starve count
References starveCnt.
increm()
bool Doodlebug::increm ()
Doodlebug::increm used to increment the starve and breed counters
Parameters
none
Returns
bool result on if the function ran properly
References breedCnt, and starveCnt.
Referenced by step().
move()
bool Doodlebug::move () virtual
Doodlebug::move() this function used finds are random neighboring unoccupied cell and moves the doodlebug form its current cell to the neighboring
Parameters
none
Returns
bool returns true if the bug was able to move
Implements Organism.
References Organism::Coordinates::cellCol, Organism::Coordinates::cellRow, col, doodlebug, empty, g, Grid::getCellOrganism(), Organism::getRandCell(), row, Grid::setCellOccupant(), Grid::setCellOrganism(), and setRowAndCol().
Referenced by Tests2::doodleMoveTest(), and step().
numPossCells()
int Doodlebug::numPossCells (int row, int col, Grid * g) virtual
Doodlebug::GetNeighbors() checks how many cells next to a doodlebug contain ants and then increments a value depending on how many neighbors are ants
Parameters
int row, the row that this cell is on
int col, the column that this cell is on
Grid g is the grid of cells
Returns
numNeighbors is the number of neighbors with ants
Reimplemented from Organism.
References ant, Grid::getCellOccupant(), and Grid::getNumCells().
Referenced by getRandCell(), and step().
setBreedCnt()
bool Doodlebug::setBreedCnt (int i)
Doodlebug::setBreedCnt Sets Breed Count
Parameters
int i sets the count to i
bool result true if the function worked
References breedCnt.
Referenced by breedDoodle().
setGridPtr()
bool Doodlebug::setGridPtr (Grid * a)
Doodlebug::setGridPtr Sets the grid pointer
Parameters
Grid* a, the new grid
Returns
bool of if the function worked
References g.
Referenced by ~Doodlebug().
setRowAndCol()
bool Doodlebug::setRowAndCol (int i, int j)
Doodlebug::setRowAndCol sets the row and column function
Parameters
int i sets the row
int j sets the col
bool result true if the function worked
References col, and row.
Referenced by eat(), and move().
setStarveCnt()
bool Doodlebug::setStarveCnt (int s)
Doodlebug::setStarveCnt() sets the starve count
Parameters
int s, the desired starve count
Returns
the starve count
References starveCnt.
Referenced by eat().
step()
bool Doodlebug::step () virtual
Doodlebug::step() tries to get the doodlebug to move or eat, then checks if the doodlebug has starved to death, then attempts to breed
Parameters
none
Returns
bool if the step worked
Implements Organism.
References breedCnt, breedDoodle(), col, eat(), g, Grid::getCellOrganism(), Grid::getNumDoodle(), increm(), move(), Organism::numPossCells(), numPossCells(), row, Grid::setNumDoodle(), starveCnt, and ~Doodlebug().
Field Documentation
breedCnt
int Doodlebug::breedCnt = 0 private
Referenced by increm(), setBreedCnt(), and step().
col
int Doodlebug::col = 0 private
Referenced by breedDoodle(), Doodlebug(), eat(), getRandCell(), move(), setRowAndCol(), step(), and ~Doodlebug().
g
Grid* Doodlebug::g = nullptr private
Referenced by breedDoodle(), Doodlebug(), eat(), getRandCell(), move(), setGridPtr(), step(), and ~Doodlebug().
row
int Doodlebug::row = 0 private
Referenced by breedDoodle(), Doodlebug(), eat(), getRandCell(), move(), setRowAndCol(), step(), and ~Doodlebug().
starveCnt
int Doodlebug::starveCnt = 0 private
Referenced by getStarveCnt(), increm(), setStarveCnt(), and step().
The documentation for this class was generated from the following files:
Doodlebug.h
Doodlebug.cpp